In [5]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.12.0'

In [6]:
#create a numpy array from a list
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [8]:
nested_list = [[1,2],[3,4],[4,6]]
nested_list

[[1, 2], [3, 4], [4, 6]]

In [9]:
#cast to numpy array
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [10]:
#generate an array
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#generates a vector of zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
#linspace creates evenly spaced array of numbers with the third argument being the number of elements to be produced
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [19]:
#create  an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
#create random arrays
#creates a uniform distribution of values between 0 nad 1
np.random.rand(2)

array([0.88657465, 0.22970517])

In [24]:
#create a matrix of random numbers
np.random.rand(3,4)

array([[0.59589157, 0.66960481, 0.00857693, 0.91459617],
       [0.89443669, 0.28600508, 0.48203761, 0.07400435],
       [0.942869  , 0.40139171, 0.540303  , 0.91312942]])

In [26]:
#get a standard normal distribution
#this means the mean is 0 and the variance is 1
np.random.randn(5,5)

array([[-0.404765  ,  0.75723561, -1.13624969,  0.38183024,  2.07273023],
       [ 2.1180777 ,  0.83398658,  0.25779745, -1.04341609, -1.60582007],
       [ 0.76934319, -0.01741041,  1.23687338,  0.01751622,  0.9802596 ],
       [-1.8669299 , -1.01260035, -0.88550082, -1.18518013, -2.50325514],
       [-0.05978081,  1.45161904,  0.69683714,  0.12515263, -0.70631278]])

In [28]:
#get the random integers
np.random.randint(0,100,20)

array([72, 81, 37, 84, 86, 59,  5,  2, 24, 65, 43, 88, 70, 26, 80, 23,  8,
        2, 10, 18])

In [29]:
#choose the same number every time by creating a seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(25)

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
#reshape array

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
#get the max value
arr.max()

24

In [38]:
#get the location for the maximum value in the array
ranarr.argmax()

7

Numpy indexing and selection

In [41]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#indexing
arr[8]

8

In [46]:
#slicing
arr[0:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
#braodcasting
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [52]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
#grab a single item
arr_2d.shape

(3, 3)

In [54]:
arr_2d[0]

array([ 5, 10, 15])

In [55]:
arr_2d[1][1]

25

In [56]:
arr_2d[0,2]

15

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
#conditional selection
arr = np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
bool_arr = arr>4

In [63]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [65]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

Numpy operations

In [66]:
arr = np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
arr.sum()

45

In [72]:
arr.mean()

4.5

In [75]:
arr2d = np.arange(0,25).reshape(5,5)

In [76]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr2d.sum()

300

In [78]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [79]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])